#!/usr/bin/env bash
# Print domain and subdomain


function print_domain_subdomain() {
	dig "$1" | awk '/ANSWER SECTION:/ {getline; sub("'"$1".'", "'"$2"'", $1); print "The subdomain " $1 " is a " $4 " record and points to " $5}'
}
#	dig "$1"  +noall +answer | awk '{split($1, subdomain, "."); print "The subdomain", subdomain[1], "is a", $4, "record and points to", $5}'



if [ "$#" -eq 2 ]
then
    print_domain_subdomain "$2.$1" "$2"
else
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1" "lb-01"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
fi
