#!/usr/bin/env bash
# Updating packages
# Installing NGINX
# Firewall Settings
# Echoing hello world
# Start NGINX


sudo apt-get -y  update
sudo apt-get -y  install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo service nginx  start
