#!/usr/bin/env bash
# Redirecting /redirect_me to youtube

sudo apt-get -y update
sudo apt-get -y install nginx

echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

ufw allow 'Nginx HTTP'

sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx restart
