#!/usr/bin/env bash
# Handing error 404 page


sudo apt-get -y update;
sudo apt-get -y install nginx;

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/page_404.html

sudo sed -i '/location / \{/i error_page 404 /page_404.html;\n\tlocation = /page_404.html {\n\troot /usr/share/nginx/html/page_404.html;\n\tinternal;\n\t}' /etc/nginx/sites-available/default

sudo service nginx start
