#!/usr/bin/env bash
# Handing error 404 page


sudo apt-get -y update;
sudo apt-get -y install nginx;

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/page_404.html

sudo sed -i "error_page 404 /page_404.html;\n\t
    location = /page_404.html {
		root /usr/share/nginx/html;\n\t
        internal;\n\t
    }" /etc/nginx/sites-available/default

sudo service nginx start
