#!/usr/bin/env bash
# Installing HAProxy

echo -e "\t>>> Updating sys, installing HAProxy and starting it...\n"
sudo apt -y  update
sudo apt install haproxy
sudo service haproxy start



echo -e "\n\t>>> Completed.\n"
