#!/usr/bin/env bash
# Backups the database


backup_file="$(date +%d-%m-%Y)".tar.gz

mysqldump -u root -p "$1" --all-databases > backup.sql
tar -cvzf "$backup_file" backup.sql

echo "Mysql backup created successfuly: $backup_file"
