#!/usr/bin/env bash
# Showing the ping for 5 times


if [[ -n "$1" ]]; then
    if [[ "$1" =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        ping -c 5 "$1"
    fi
else
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 1
fi
