#!/usr/bin/env bash
# FizzBuzz Game

num=1
while [[ $num -le 100 ]]
do
	if [ $(( num % 15 )) -eq 0 ];then
		echo "FizzBuzz"
	elif [ $(( num % 3 )) -eq 0 ]; then
		echo "Fizz"
	elif [ $(( num % 5 )) -eq 0 ]; then
		echo "Buzz"
	else
		echo "$num"
	fi

	num=$(( num + 1 ))
done

