#!/usr/bin/env bash
# use while loop to print "Best School" 10 times
# and print "Hi" at the 9th iteration

i=0
while [ $i -lt 10 ]
do
	echo "Best School"
	if [ $i -eq 8 ]; then
		echo "Hi"
	fi
	i=$(( i + 1 ))
done

