#!/usr/bin/env bash
# using while loop to print "Best School' 9 times
# and print "bad luck" at the 4th iteration &
# "good luck" at the 8th iteration

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 4 ]; then
		echo "bad luck"
	elif [ $i -eq 8 ]; then
		echo "good luck"
	else
		echo "Best School"	
	fi
	i=$(( i + 1 ))
done

