#!/usr/bin/env bash
# print hours from 0 - 12 and minutes from 1-59

h=0
while [ $h -le 12 ]
do
	min=1
	echo "Hour:" $h
	while [ $min -le 59 ]
	do
		echo $min
		min=$(( min + 1 ))
	done
	h=$(( h + 1 ))
done

