#!/usr/bin/env bash
# Change IP for localhost and facebook

sudo cp /etc/hosts /etc/hosts_backup
sudo sed -i 's/^127\.0\.0\.1/127\.0\.0\.2/' /etc/hosts
echo "8.8.8.8	www.facebook.com" | sudo tee -a /etc/hosts
echo "8.8.8.8	facebook.com" | sudo tee -a  /etc/hosts
