#!/usr/bin/env bash
# Change IP for localhost and facebook

sudo cp /etc/hosts ~/hosts.new

sudo sed -i 's/^127\.0\.0\.1/127\.0\.0\.2/' ~/hosts.new
echo "8.8.8.8	www.facebook.com" | sudo tee -a ~/hosts.new
echo "8.8.8.8	facebook.com" | sudo tee -a  ~/hosts.new

sudo cp -f ~/hosts.new /etc/hosts
