#!/usr/bin/env bash
# Make it sweet and just 7 lines
wget -O 100_helper https://raw.githubusercontent.com/samehelgazar95/alx-system_engineering-devops/master/0x12-web_stack_debugging_2/100-helper
chmod u+x 100_helper
./100_helper
